#!/bin/sh

setwall -q -n -t monokai
xrdb -merge ~/.config/X11/Xresources/main

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
picom --experimental-backends &
mpd &
unclutter &
parcellite -n &
safeeyes -e &
dunst &
asus-fan-daemon &
nm-applet &
libinput-gestures &

dwmblocks &
exec dwm
