#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
        # shellcheck disable=1090
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

[ "$(supergfxctl -g)" = "Hybrid" ] && autorandr -c >/dev/null 2>&1
rswal --variables no-reload=1

autostart="\
    /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
    picom
    mpd --no-daemon
    musicup
    unclutter
    parcellite -n
    safeeyes
    nm-applet
    $STATUSBAR"

echo "$autostart" | while read -r program; do
    process="${program%%[[:space:]]*}"
    process="${process##*/}"
    pidof -s "$process" || $program >"/tmp/$process.log" 2>&1 &
done

exec dwm >/tmp/dwm.log 2>&1
