#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

setwall -q -n -t monokai

# mpd is started by default by systemd
autostart="\
    picom
    unclutter
    parcellite -n
    safeeyes
    asus-fan-daemon
    nm-applet
    $STATUSBAR"

echo "$autostart" | while read -r program; do
    pidof -s "${program%%[[:space:]]*}" || $program >"/tmp/$(basename "$program").log" 2>&1 &
done

exec dwm >/tmp/dwm.log 2>&1
