return {
	rosewater = "{{colors.special.cursor}}",
	flamingo = "#f2cdcd",
	pink = "{{colors.normal.magenta}}",
	mauve = "#cba6f7",
	red = "{{colors.normal.red}}",
	maroon = "#eba0ac",
	peach = "#fab387",
	yellow = "{{colors.normal.yellow}}",
	green = "{{colors.normal.green}}",
	teal = "{{colors.normal.cyan}}",
	sky = "#89dceb",
	sapphire = "#74c7ec",
	blue = "{{colors.normal.blue}}",
	lavender = "#b4befe",
	text = "{{colors.special.foreground}}",
	subtext1 = "{{colors.normal.white}}",
	subtext0 = "{{colors.bright.white}}",
	overlay2 = "{{darken colors.bright.white 0.115}}",
	overlay1 = "{{saturate (darken colors.bright.white 0.23) 0.02}}",
	overlay0 = "{{saturate (darken colors.bright.white 0.34) 0.02}}",
	surface2 = "{{colors.bright.black}}",
	surface1 = "{{colors.normal.black}}",
	surface0 = "{{saturate (darken (shiftHue colors.normal.black 3) 0.26) 0.035}}",
	base = "{{colors.special.background}}",
	mantle = "{{darken colors.special.background 0.2}}",
	crust = "{{darken colors.special.background 0.42}}",
}
