theme: catppuccin

variables:
  alpha: 0.85
  icon-theme: Papirus-Dark
  gap: 10

hooks:
  - set-wallpaper.sh
  - update-xrdb.sh
  - reload-ui.sh

templates:
  - source: colors.gtk
    target: ~/.config/waybar/colors.css
  - source: colors.rasi
    target: ~/.config/rofi/themes/colors.rasi
  - source: dunstrc
    target: ~/.config/dunst/dunstrc
  - source: suckless.xresources
    target: ~/.config/X11/Xresources/suckless
  - source: nvim.lua
    target: ~/.config/nvim/lua/util/colors.lua
  - source: colors.hyprland
    target: ~/.config/hypr/colors.conf
  - source: colors.foot
    target: ~/.config/foot/colors.ini
  - source: colors.sh
    target: ~/.cache/rswal/colors.sh
  - source: colors.tofi
    target: ~/.config/tofi/colors
  - source: fnott.ini
    target: ~/.config/fnott/fnott.ini
  - source: rmpc.ron
    target: ~/.config/rmpc/themes/base-16.ron
