theme: catppuccin

variables:
  alpha: 0.85

hooks:
  - set-wallpaper.sh
  - update-xrdb.sh
  - reload-ui.sh

templates:
  - source: colors.rasi
    target: ~/.config/rofi/themes/colors.rasi
  - source: dunstrc
    target: ~/.config/dunst/dunstrc
  - source: suckless.xresources
    target: ~/.config/X11/Xresources/suckless
  - source: colors.lua
    target: ~/.config/nvim/lua/util/colors.lua
