theme: catppuccin

variables:
  alpha: 0.85
  icon-theme: Papirus-Dark
  gap_outer: 20
  gap_inner: 10

hooks:
  - set-wallpaper.sh
  - update-xrdb.sh
  - reload-ui.sh

templates:
  - source: colors.gtk
    target: ~/.config/waybar/theme.css
  - source: waybar.css
    target: ~/.config/waybar/colors.css
  - source: colors.rasi
    target: ~/.config/rofi/themes/colors.rasi
  - source: overrides.dunstrc
    target: ~/.config/dunst/dunstrc.d/10-overrides.conf
  - source: suckless.xresources
    target: ~/.config/X11/Xresources/suckless
  - source: nvim.lua
    target: ~/.config/nvim/lua/util/colors.lua
  - source: variables.hyprland
    target: ~/.config/hypr/variables.conf
  - source: colors.sh
    target: ~/.cache/rswal/colors.sh
  - source: rmpc.ron
    target: ~/.config/rmpc/themes/base-16.ron
