#!/bin/sh

# Set charge limit for ASUS battery on suspend/resume
cacheFile="/var/cache/charge-threshold"
thresholdFile="/sys/class/power_supply/BAT0/charge_control_end_threshold"
case "$1" in
	suspend)
		echo "Caching charge threshold on suspend..."
		cat $thresholdFile > $cacheFile
		;;
  	resume)
		echo "Restoring charge threshold on resume..."
		cat $cacheFile > $thresholdFile
		;;
esac
