#!/bin/sh

cards="/sys/class/backlight/amdgpu_bl0 /sys/class/leds/asus::kbd_backlight"

# Restore saved brightness for each card, if any.
for card in $cards; do
	cacheFile=/var/cache/backlight/$(basename $card)
	[ -r $cacheFile ] && echo $(cat $cacheFile) > $card/brightness
done

exec chpst -b backlight pause
