#!/bin/bash

# Only proceed if bash is running interactively.
case $- in
    *i*) ;;
    *) return ;;
esac

# History settings.
HISTFILE="$XDG_STATE_HOME/bash/history"
HISTSIZE=1000
HISTFILESIZE=2000
HISTCONTROL=ignoreboth # Ignore duplicates or lines starting with a space.

history_dir="${HISTFILE%/*}"
[ ! -d "$history_dir" ] && mkdir -p "$history_dir"
unset history_dir

shopt -s histappend

# Check if the terminal supports colors.
if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
    # We have color support; assume it's compliant with Ecma-48
    # (ISO/IEC-6429). (Lack of such support is extremely rare, and such
    # a case would tend to support setf rather than setaf.).
    color_prompt=1
else
    color_prompt=0
fi

if [ $color_prompt -ne 0 ]; then
    PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='\u@\h:\w\$ '
fi
unset color_prompt

# If this is an xterm, set the title to user@host:dir.
case "$TERM" in
    xterm* | rxvt*)
        PS1="\[\e]0;\u@\h: \w\a\]$PS1"
        ;;
    *) ;;
esac

# Enable programmable completion configurations.
if ! shopt -oq posix; then
    if [ -f /usr/share/bash-completion/bash_completion ]; then
        . /usr/share/bash-completion/bash_completion
    elif [ -f /etc/bash_completion ]; then
        . /etc/bash_completion
    fi
fi

# Source common shell configurations.
shell_config="$XDG_CONFIG_HOME/shellrc"
[ -f "$shell_config" ] && . "$shell_config"
unset shell_config

PROMPT_COMMAND='printf "\033]0;%s@%s:%s\007" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/"~"}"'
