"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

# TODO:
# - Tab switching hotkey to Shift+[h|l]
# - Fuzzy finding with Ctrl+f
# - Figure out file selections
# - On smaller screens, hide parent pane
# - bat previews or theming

[[manager.prepend_keymap]]
desc = "Open shell here"
on = ["$"]
exec = 'shell "$SHELL" --block --confirm'

[[manager.prepend_keymap]]
desc = "Drag selected files"
on = ["f", "d"]
exec = '''
	shell 'dragon-drop --on-top --and-exit "$1"' --confirm
'''

[[manager.prepend_keymap]]
on = ["l"]
exec = "plugin --sync smart-enter"
desc = "Enter the directory, or open the file"

[[input.prepend_keymap]]
on = ["<Esc>"]
exec = "close"
desc = "Cancel input"
