# If the user's terminal is in dark mode, Yazi will load `theme-dark.toml` on startup; otherwise, `theme-light.toml`.
# You can override any parts of them that are not related to the dark/light mode in your own `theme.toml`.

# If you want to dynamically override their content based on dark/light mode, you can specify two different flavors
# for dark and light modes under `[flavor]`, and do so in those flavors instead.
"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

[manager]
count_copied = { fg = "reset" }
count_cut = { fg = "reset" }
count_selected = { fg = "reset" }

[status]

[mode]
normal_main = { fg = "black", bg = "blue", bold = true }
normal_alt = { fg = "blue", bg = "black" }

select_main = { fg = "black", bg = "green", bold = true }
select_alt = { fg = "green", bg = "black" }

unset_main = { fg = "black", bg = "red", bold = true }
unset_alt = { fg = "red", bg = "black" }


[which]
mask = { bg = "black" }
separator_style = { fg = "gray" }


[help]
footer = { fg = "reset", bg = "reset", reversed = true }

[icon]
dirs = [
    { name = "desktop", text = "" },
    { name = "development", text = "" },
    { name = "documents", text = "" },
    { name = "downloads", text = "" },
    { name = "movies", text = "" },
    { name = "music", text = "" },
    { name = "pictures", text = "" },
    { name = "public", text = "" },
    { name = "videos", text = "" },
]
