#!/bin/sh

## Enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
	test -r ~/.dircolors && eval "$(dircolors -b ~.dircolors)" \
	|| eval "$(dircolors -b)"

    alias \
	    ls="ls --color=auto" \
	    grep="grep --color=auto" \
	    fgrep="fgrep --color=auto" \
	    egrep="egrep --color=auto"
fi

alias \
	dosbox="dosbox -conf "$XDG_CONFIG_HOME"/dosbox/dosbox.conf" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query"
