#!/bin/sh

alias \
    cat="bat" \
    cbcopy="xclip -selection clipboard" \
    cbpaste="xclip -selection clipboard -out" \
    cmatrix="unimatrix -n -s 96 -l o" \
    diff="diff --color=auto" \
    docker="nerdctl" \
    dosbox="dosbox -conf \$XDG_CONFIG_HOME/dosbox/dosbox.conf" \
    egrep="egrep --color=auto" \
    fgrep="fgrep --color=auto" \
    grep="grep --color=auto" \
    ll="ls -l" \
    ls="ls --color=auto" \
    ncdu="ncdu --color dark" \
    open="xdg-open" \
    tree="tree -a -I .git" \
    vi="nvim" \
    yarn='yarn --use-yarnrc "$XDG_CONFIG_HOME/yarn/config"'
