#!/bin/sh

scripts="$XDG_CONFIG_HOME/aliasrc
    $XDG_CONFIG_HOME/lf/lfcd.sh
    /usr/share/z/z.sh
    /opt/ros/noetic/setup.sh"

echo "$scripts" | while read -r script; do
    if [ -f "$script" ]; then
        source "$script"
    fi
done

se() {
    scripts="$(find ~/.local/bin/ -type l | grep -v /bin/statusbar)
$(find ~/.local/bin/statusbar/ -type f)"
    echo "$scripts" | fzf | xargs -r "$EDITOR"
}
