#!/bin/sh

# Source shell aliases
if [ -f "$XDG_CONFIG_HOME/aliasrc" ]; then
	source "$XDG_CONFIG_HOME/aliasrc"
fi

# Source lfcd command, if it exists
LFCD="$XDG_CONFIG_HOME/lf/lfcd.sh"
if [ -f "$LFCD" ]; then
    source "$LFCD"
fi

# Source nnncd command, if it exists
NNNCD="$XDG_CONFIG_HOME/nnn/nnncd.sh"
if [ -f "$NNNCD" ]; then
    source "$NNNCD"
fi

# NVM
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
