[terminal]
# The VT to run the greeter on. Can be "next", "current" or a number
# designating the VT.
vt = current

# The default session, also known as the greeter.
[default_session]
command = "tuigreet --remember --remember-session --sessions /etc/tuigreet/sessions"

# The user to run the command as. The privileges this user must have depends
# on the greeter. A graphical greeter may for example require the user to be
# in the `video` group.
user = "greeter"
