return {
    "windwp/nvim-autopairs",
    opts = {}
}
--
-- autopairs.setup({
--     -- modifies the function or method delimiter by filetypes
--     map_char = {
--         all = "(",
--         tex = "{",
--     },
--
--     -- check bracket in same line
--     enable_check_bracket_line = false,
--
--     -- check treesitter
--     check_ts = true,
--     ts_config = {
--         lua = { "string", "source" },
--         javascript = { "string", "template_string" },
--         java = false,
--     },
--     disable_filetype = { "TelescopePrompt", "spectre_panel" },
--     ignored_next_char = string.gsub([[ [%w%%%'%[%"%.] ]], "%s+", ""),
--     enable_moveright = true,
--
--     -- disable when recording or executing a macro
--     disable_in_macro = false,
--
--     -- add bracket pairs after quote
--     enable_afterquote = true,
--
--     -- map the <BS> key
--     map_bs = true,
--
--     -- don't map <c-w> to delete a pair if possible
--     map_c_w = false,
--
--     -- disable when insert after visual block mode
--     disable_in_visualblock = false,
--
--     -- change default fast_wrap
--     fast_wrap = {
--         map = "<M-e>",
--         chars = { "{", "[", "(", '"', "'" },
--         pattern = string.gsub([[ [%'%"%)%>%]%)%}%,] ]], "%s+", ""),
--         offset = 0, -- Offset from pattern match
--         end_key = "$",
--         keys = "qwertyuiopzxcvbnmasdfghjkl",
--         check_comma = true,
--         highlight = "Search",
--         highlight_grey = "Comment",
--     },
-- })
--
-- -- Enable nvim-cmp integration
-- local status_ok, cmp = pcall(require, "cmp")
-- if status_ok then
--     local cmp_autopairs = require("nvim-autopairs.completion.cmp")
--     cmp.event:on("confirm_done", cmp_autopairs.on_confirm_done())
-- end
--
-- -- Enable treesitter integration
-- local status_ok, tsConfigs = pcall(require, "nvim-treesitter.configs")
-- if status_ok then
--     tsConfigs.setup({ autopairs = { enable = true } })
--     local tsConds = require("nvim-autopairs.ts-conds")
--     local rule = require("nvim-autopairs.rule")
--
--     -- press % => %% is only inside comment or string
--     autopairs.add_rules {
--         rule("%", "%", "lua"):with_pair(tsConds.is_ts_node { "string", "comment" }),
--         rule("$", "$", "lua"):with_pair(tsConds.is_not_ts_node { "function" }),
--     }
-- end
