require("plugins.impatient") -- has to be at the top
require("plugins.packer")
require("plugins.alpha")
require("plugins.autopairs")
require("plugins.autotag")
require("plugins.bufferline")
require("plugins.colorizer")
require("plugins.comment")
require("plugins.git")
require("plugins.gitsigns")
require("plugins.indentline")
require("plugins.lualine")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.vimwiki")
require("plugins.web-devicons")
